#!/bin/sh

cmd='emacsclient -n -a "/usr/bin/vim"'

# TODO: parse result from grep/ack and change file.ext:line to +line file.ext
if [ $# -eq 1 ];
then
    args=`echo $1 | perl -ne 'print if s/(.*):(\d+):?/+$2 $1/'`
#    cmd=echo
    if [ "x$args" != "x" ];
    then
        $cmd $args
    else
        $cmd $1
    fi
else
    $cmd "$@"
fi
tmux select-window -t emacs
