#!/bin/bash
# fast run script to visualize common commands
#
# sample lines from ~/.rbookmarks:
# libreoffice@@
# qms@@unset ORACLE_HOME; LC_TIME="en_US.UTF-8" WINEPREFIX=~/.wine32 wine myexe.exe


t=$(perl -ne 'print if s/(.*)@@.*/$1/;' < ~/.rbookmarks | dmenu)

cmd=$(grep $t ~/.rbookmarks |awk -F@@ '{print $2; exit}')
if [ -z "$cmd" ]; then
     cmd=$(grep $t ~/.rbookmarks |awk -F@@ '{print $1; exit}')
fi
if [ -z "$cmd" ]; then
    echo "No matching command found. Exiting"
    exit
fi

echo $cmd
eval "$cmd" &
