#!/bin/sh
# find some C/C++ language definition
# typedef
# struct definition
# or macro defined by define

# use source grepping tool you prefer here
# perl thing
mygrep="ack-grep --nogroup "
# pythonish one
#mygrep=pss

pat=$1
shift

echo  going to find $pat at $*
# todo add ffip support when possible

$mygrep "typedef.*$pat;" $*
$mygrep "struct $pat[\s{]*$" $*
$mygrep "class $pat\W?[{:]" $*
$mygrep "#\s*define.*\W$pat[\s(]" $*
$mygrep "}\s*$pat[\W ]?;" $*

exit 0

