#!/bin/sh
# find file in project
# when call without arg returns root project path
# root of project determined by .git/.hg/etc. folder

pattern="-d .git -o -d .hg -o -d .projectroot -o -f Cargo.toml -o -f README.md -o -d .idea -o -d .projectile"
curdir=$(pwd)
while [ "x$(pwd)" != "x/" ]; do
    if [ $pattern ]; then
        if [ "x$1" != "x" ]; then
            find "$(pwd)" -iname "$@"
        else
            pwd
        fi
        break
    else
        cd ..
    fi
done
cd "$curdir"
