#!/bin/sh
# find file in project
# when call without arg returns root project path
# root of project determined by .git/.hg/etc. folder

pattern="-d .git -o -d .hg -o -d .projectroot -f Cargo.toml -f README.md"
curdir=$(pwd)
while [ "x$(pwd)" != "x/" ]; do
    if [ "$pattern" ]
    then
        if [ "x$1" != "x" ];
        then
            find "$(pwd)" -iname "$@"
            break
        fi
        pwd
        break;
    else
        cd ..
    fi
done
cd "$curdir"
