#!/bin/bash

arg="$(echo $* | sed 's/ //g')"

for b in x-www-browser google-chrome firefox opera; do
    if $(which $b &> /dev/null; echo $?);
    then
        case $b in
            firefox)
                browser="firefox -new-tab"
                ;;
            *)
                browser="$b"
                ;;
        esac
    fi
done
$browser http://www.haskell.org/hoogle/?hoogle=$arg

