#!/usr/bin/env python
#-*- coding: utf-8 -*-
#
# File: resuse.py
#
# Created: Saturday, March  3 2012 by Stan. S. Krupoderov
#
# Description: see Usage

import sys
import resource
from  getopt import getopt
from subprocess import Popen

class RUsage():
    pass

ru = RUsage()
ru.utime =	 0  #	time in user mode (float)
ru.stime =	 1  #	time in system mode (float)
ru.maxrss =      2  #	maximum resident set size
ru.ixrss =	 3  #	shared memory size
ru.idrss =	 4  #	unshared memory size
ru.isrss =	 5  #	unshared stack size
ru.minflt =      6  #	page faults not requiring I/O
ru.majflt =      7  # 	page faults requiring I/O
ru.nswap =	 8  #	number of swap outs
ru.inblock =     9  #	block input operations
ru.oublock =  10    #	block output operations
ru.msgsnd =   11    #	messages sent
ru.msgrcv =   12    #	messages received
ru.nsignals = 13    #	signals received
ru.nvcsw =    14    #	voluntary context switches
ru.nivcsw =   15    #


USAGE = """
DESCRIPTION:
   Execute command and return it's resourse usage info
USAGE:
   %s [-h|-x|-m|-t] command_name
OPTIONS:
   -h - this help
   -m - just memory usage info
   -t - just time usage info
   -x - extended info
""" % sys.argv[0]
opts, args = getopt(sys.argv[1:], "hxmt")

opt = {}
for k,v in opts:
    opt[k] = v

if ("-h" in opt
    or len(opt) == 0
    or opt.keys()[0] not in ("-x", "-m", "-t")
    or len(args) == 0):
    print USAGE
    sys.exit(0)
mode = opt.keys()[0]

p  = Popen(args).wait()
usage = resource.getrusage(resource.RUSAGE_CHILDREN)
if mode == "-m":
    print "MAX RSS: ", usage[ru.maxrss]
elif mode == "-t":
    print "Time, system(%s), user(%s):" % (usage[ru.stime], usage[ru.utime])
elif mode == "-x":
    for name, desc in [
        ('ru_utime', 'User time'),
        ('ru_stime', 'System time'),
        ('ru_maxrss', 'Max. Resident Set Size'),
        ('ru_ixrss', 'Shared Memory Size'),
        ('ru_idrss', 'Unshared Memory Size'),
        ('ru_isrss', 'Stack Size'),
        ('ru_inblock', 'Block inputs'),
        ('ru_oublock', 'Block outputs'),
    ]:
        print '%-25s (%-10s) = %s' % (desc, name, getattr(usage, name))
    print "-"*30

