#!/bin/sh

if [ $# -eq 1 ]; then
  selected=$1
else
  if [ -n "$TMUX_SESSION_OPTIONS" ]; then
    # shellcheck disable=SC2086
    selected=$(find $TMUX_SESSION_OPTIONS -mindepth 1 -maxdepth 1 -type d | fzf)
  fi
fi

if [ -z "$selected" ]; then
  exit 0
fi

# some directory selected
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [ -z "$TMUX" ] && [ -z "$tmux_running" ]; then
  tmux new-session -s "$selected_name" -c "$selected"
  exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
  tmux new-session -d -s "$selected_name" -c "$selected"
  # tmux new-session -d -s "$selected_name" -c "$selected" "$SHELL"
fi

tmux switch-client -t "$selected_name"
# tmux new-session -s home -d -n "#" "sudo -s"

# vim: softtabstop=2 shiftwidth=2 expandtab :
