#!/usr/bin/env python

import sys

HEADER = '\033[95m'
OKBLUE = '\033[94m'
OKGREEN = '\033[92m'
WARNING = '\033[93m'
FAIL = '\033[91m'
ENDC = '\033[0m'
BOLD = "\033[1m"

def _wrap_with(code):

    def inner(text, bold=False):
        c = code
        if bold:
            c = "1;%s" % c
        return "\033[%sm%s\033[0m" % (c, text)
    return inner

red = _wrap_with('31')
green = _wrap_with('32')
yellow = _wrap_with('33')
blue = _wrap_with('34')
magenta = _wrap_with('35')
cyan = _wrap_with('36')
white = _wrap_with('37')

skip = True
for line in sys.stdin:
    # skip till ---
    if "---" in line:
        skip = False

    if (skip):
        # print "%s skipped" % line
        print
        continue

    if (sys.stdout.isatty()):
        sys.stdout.write(
            line.replace(
                "Passes", OKGREEN+"Passes"+ENDC).replace(
                "Fails", FAIL+"Fails"+ENDC).replace(
                "F", FAIL+"F"+ENDC).replace(
                ".", OKGREEN+"."+ENDC).replace(
                ")", BOLD+")"+ENDC).replace(
                "(", BOLD+"("+ENDC).replace(
                "OK", BOLD+"OK"+ENDC)
        )
    else:
        sys.stdout.write(line)
