#!/usr/bin/env python
#-*- coding: utf-8 -*-
#
# File: vgrep
# Description: see USAGE

import sys
from  getopt import getopt

USAGE = """
DESCRIPTION:
   Greping all lines not match patterns like chain of
   grep -v arg1 | grep -v arg2
USAGE:
   %s <args>
OPTIONS:
   -h - this help
""" % sys.argv[0]

opts, args = getopt(sys.argv[1:], "h")
opt = {}
for k,v in opts:
    opt[k] = v

if ("-h" in opt) or 1 == len(sys.argv):
    print USAGE
    sys.exit(0)

for line in sys.stdin:
    print_p = True
    for arg in sys.argv:
        if arg in line:
            print_p = False
    if print_p:
        print line,







